### ISSUE TITLE
GPX file import is failing on iOS

### ISSUE THREAD

**Issue by DominikHerold** [osmandapp/OsmAnd-iOS#1133]
### Description
I tried to import a GPX file for the first time but it failed with an error message.

### How to reproduce?
Open file app on iPhone. Select the gpx file. Touch share button and open with _OsmAnd Maps_
Error message will appear. Unfortunately I have only a german error message:
_Tracks importieren__
_Angegebene GPX-Datei kann nicht importiert werden_

### Your Environment
OsmAnd Version: 3.9.7
Android/iOS version: iOS 14.4
Device model: iPhone SE

**Maps used (online or offline):**   
Using the Offline map of Saxony (Germany // Europe).

![2E9D5EB2-9C18-4685-890F-762BB88E1A07](https://user-images.githubusercontent.com/23322571/111982684-8eb31680-8b09-11eb-8d52-ff8657b27f05.png)

[20210321014711-58137-data.txt](https://github.com/osmandapp/OsmAnd/files/6181731/20210321014711-58137-data.txt)
(Renamed the GPX file from *.gpx to *.txt due to limitations of GitHub)

**Comment by PaulStets** [comment]
@DominikHerold Please make sure you use the latest version of the app. I have checked your track and it works with the latest version.

**Comment by DominikHerold** [comment]
Unfortunately I'm already using the latest Version for iOS: 3.9.7.
@PaulStets Did you open the gpx the same way I described? Maybe there is another way to open it?

**Comment by PaulStets** [comment]
@DominikHerold I just uploaded your track to the Telegram app and was able to open it in OsmAnd from there. I also managed to successfully import your file to OsmAnd from the Files app. Generally, the app you use to share the file with OsmAnd does not matter, but if you can, please try to send the file from another app. Also, please double-check that you have the latest version from the App Store, because this issue looks like something we fixed a couple of releases ago. Let me know how it works out.

**Comment by habitoti** [comment]
I was just preparing a bike tour that I wanted to start tomorrow, and I am facing the same issue. On iPhone, I can‘t import any of my 5 tracks freshly exported from Komoot. I am using latest OSMAND version 4.4.1. Import of the same GPX files works w/o issues on OSMAND on iPad, however iPhone fails with the error shown above. Tried all sorts of imports (directly from OSMAND, shared from saved iCloud file, shared directly from Komoot to OSMAND) — all with the same result.
