### ISSUE TITLE
sea display bug

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1533]
http://osmand.net/go.html?lat=43.20973&lon=5.43552&z=14 The location was shared with you by OsmAnd

![image](https://user-images.githubusercontent.com/79785663/136519573-604134f5-fa70-49af-94d4-140bc702798f.png)![image](https://user-images.githubusercontent.com/79785663/136519625-3a8a9e7e-f8e7-4f32-9bcb-af614b8ad01c.png)![image](https://user-images.githubusercontent.com/79785663/136519691-7e09357e-89df-4034-9387-1b7bc2f462b9.png)![image](https://user-images.githubusercontent.com/79785663/136519768-997c0c01-5dab-4aa1-ad98-180d7f9066c7.png)

**Comment by ivanPyrohivskyi** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/pull/280

<img src="https://user-images.githubusercontent.com/1040293/145170017-ab7dd5b2-963b-4fc2-ab24-feb387d62faf.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/145170026-056b9f47-356f-43b5-a3c6-8966b24d792e.png" width="400"/>
