### ISSUE TITLE
sqlitedb rastermaps dont load 4.2

### ISSUE THREAD

**Issue by gschlad** [osmandapp/OsmAnd-iOS#1984]
it´s not possible to load any sqlite raster maps (e.g. from this source https://info.skitourenguru.ch/index.php/swisstopo4guru) with version 4.2

i also tested it with other maps sources based on mbtiles2osmand.py, Globalmapper and Mobac. The same map´s work just fine on the latest android verison.

**Comment by maartenk** [comment]
Same issue mentioned below. And i can also confirm the issue. 

> Adding here since it seems to be related: 
We are no longer able to display imported sqlitedb raster layers in version 4.2. Osmand appears to recognize the filetype, but raster layers will not display as overlays or underlays since the 4.2 update.

_Originally posted by @StrikeLines in https://github.com/osmandapp/OsmAnd-iOS/issues/1972#issuecomment-1136263481_

**Comment by vshcherb** [comment]
It's fixed and now we have 1) Public Beta 4.2.4 which is under review for Apple.

Please try public beta via testflight meanwhile https://docs.osmand.net/docs/versions/future-ios
