### ISSUE TITLE
Vehicle parameters not saving by delimiter point usage

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2470]
### Description
Change the vehicle parameters with the default values, saving is working. But if you use the delimiter point yourself, the value gets deleted.

even if you use the default parameter, save it, open again and save it again, it is gone.

Only working delimiter is comma for manual input.

region set to Auto but same with Europe set
Length is set to meters/km

<table style="width:700%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/35132439/212532450-ec8c9404-9f59-4fc2-8d6c-65a7d1af3a28.jpeg"  width="600" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/212532451-36d087bd-17b9-41f3-969b-378403c92ad0.jpeg"  width="600" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/212532453-66a3893d-f592-45bd-8a37-7891f7564973.jpeg"  width="600" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/212532454-33d90dc6-eeae-452e-8094-c3eb1beca2ad.jpeg"  width="600" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?
Set a value with a delimiter point and save it.

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: iOS 16.2
Device model: iPhone 14 pro , iPad pro

**Comment by Skalii** [comment]
works correctly on 4.3.4

**Comment by Zirochkabila** [comment]
4.4.5.2
Still present

https://user-images.githubusercontent.com/104760013/215803652-9478729f-9eb8-4bbf-8896-777def02744a.mp4

**Comment by dmpr0** [comment]
## How to reproduce
iPad and German keyboard is needed. iPad needed because on iPhone's by default open numpad without ability to switch languages or enter other characters, but on iPad full QWERYU keyboard will be opened.
* Add German keyboard in iOS settings
* On iPad open **Menu** – **Settings** – **Configure Profile** – **Navigation settings** – **Vehicle parameters** – **Weight limit**
* Tap on input field
* Switch keyboard language to **German**, and switch mode to numbers
* Enter first number then tap on button with `?` and `.`
* Tap **Done**
* Enter valued not be saved.

<img src="https://user-images.githubusercontent.com/9365308/216305888-8b4608de-b63a-4160-ad21-1297ae601baa.png"  width="500" height="auto"/>

**Comment by Skalii** [comment]
[Fix vehicle parameters - decimal separator input](https://github.com/osmandapp/OsmAnd-iOS/pull/2550)

**Comment by dmpr0** [comment]
- [ ]  Don't work at all on iPhone
TestFlight 4.4.5.6, 
<video source src="https://user-images.githubusercontent.com/9365308/218507740-86f7eb6f-3f60-4de4-b8cf-4d0dfb3c19e2.MP4"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Vehicle parameters - fix decimal separator input considering system locale r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2575)

**Comment by dmpr0** [comment]
## Review
- [ ]  Don't work on iPad. Build from master

**Comment by Skalii** [comment]
[Vehicle parameters - fix comma input (r4.3)](https://github.com/osmandapp/OsmAnd-iOS/pull/2585)
