### ISSUE TITLE
Unable to import GPX files, thru My Places – Favorites – Import favorites.

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2507]
Reproduced on iPhone 12S but not on all other devices. Feedback is wanted
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/214270046-febd1887-7476-4467-9d6c-efb1b13d2e1c.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by drtbyk** [comment]
v4.4.5.4
iPhone 14Pro Max, iOS v16.3.1

I **have** been able to Export favorites but only if I **do not** select individual waypoints. It will only export the entire contents of My Favorites.

In addition, the Export button is below the bottom Menu bar: see below.  

![IMG_3600](https://user-images.githubusercontent.com/8745955/221367013-b72f1cdb-e204-41a0-a7a6-16182dd1a10e.png)

**Comment by vshcherb** [comment]
There is a workaround, you need to first open Files application and click on Favorites.gpx file in that case you should be able to import points as favorites.
2nd workaround is to open GPX file and then convert points to favorites

**Comment by jmendys** [comment]
> There is a workaround, you need to first open Files application and click on Favorites.gpx file in that case you should be able to import points as favorites. 2nd workaround is to open GPX file and then convert points to favorites

This won't work if GPX files are assigned to another application. Can someone advice how to make OsmAnd default app for GPX files?

Also mind that this workaround will crash OsmAnd if your total number of favorites exceeds 10.000.

**Comment by dorjanbenic** [comment]
After update of iOS (17.1) on my iPhone 13 I have reinstalled latest version of OsmAnd, 4.5.5 i think. Then I have tried to import GPX file again (one I exported from OsmAnd) and it worked. Now every GPX tile I browse to in iOS file picker is not greyed out any more. 

Not sure if the issue was resolved by updating iOS or by reinstalling OsmAnd app. 

I guess some files remain on iOS (cache/configuration file) that is not deleted by deleting the app. Probably iOS upgrade process deletes some temporary files so new installation of OsmAnd is clean. On MacOS I can manually delete cache/configuration files but not on iOS.

**Comment by dmpr0** [comment]
Tested on TestFlight 4.6.1.3

<table style="width:100%">
  <tr>
    <th>Import favorites</th>
    <th>Import tracks</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/41225538-0d28-4e6d-82ad-8ea32e0a2568"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c505374b-34b5-498d-b3a2-439fcaafece8"  width="300" height="auto"/> </td>
  </tr>
</table>   

* All type of .gpx files are unavailable thru Favorites > Import Favorites
