### ISSUE TITLE
Routing is not using OsmAnd Live data

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#255]
I've modified a previously existing road on OSM to set it as under construction. This modifications have been integrated in my app with OsmAnd live. But when I create a new route, the app seems to only consider "base" data and not live updates. I know there is a setting in navigation called "OsmAnd Live navigation" but it constantly and automatically switch off as soon as I quit the settings menu.

**Comment by PaulStets** [comment]
Closed with #256. Sorry for the inconvenience. It will be fixed in the next update. By the way, the option should still work regardless of the indicator. Please try to enable it via settings, then restart OsmAnd and try to calculate the route. If no luck, please go to the settings and repeat the operation. Let me know if it helps.

**Comment by natolh** [comment]
Well, I didn't test your case because my phone went out of battery, and after launching OsmAnd everything was working correctly.

**Comment by PaulStets** [comment]
Glad it worked out. Anyway, the setting will be fixed in the next update.
