### ISSUE TITLE
Split interval does not work correctly

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2600]
When enabling split interval by distance application duplicates the value.
OsmAnd 4.3.4
[2023 E2 Westhumble - Disley.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10814648/2023.E2.Westhumble.-.Disley.gpx.zip)

<img src="https://user-images.githubusercontent.com/80623554/220581298-4f9c6aae-7b7d-4734-a121-4338dbc1b8b0.png"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
4.4.5.8
OsmAnd~ 4.4.0#14206mqta, Released: 2023-02-27

Duplication occurs due to the fact that the interval of the entire track and its individual parts is displayed simultaneously.
For example, how the intervals on the same sections look in Android

<details><summary>Interval</summary>
<img width="240" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221559966-15837531-1402-47e8-810e-01335be78452.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221559970-3520760c-7a12-4518-9c07-c4ecfbf709cc.jpeg">
</details> 


<details><summary>Interval</summary>
<img width="240" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221560447-737f988c-7748-458b-a17a-815e3c9d2a87.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221560449-b824af88-ba66-41fd-80b8-87ba11b8c408.jpeg">
</details>

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/096e15470a97ea7ed3ebe3d78979a9790ae62539

**Comment by dmpr0** [comment]
Done
<img src="https://user-images.githubusercontent.com/9365308/232734867-a25792b9-e6c3-459c-be63-89536c1c9d60.png"  width="300" height="auto"/>
