### ISSUE TITLE
[bug] bike navigation issue

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2812]
In OsmAnd 4.4, i got sometimes inconsistent routing. For exemple here off-road, going to the first stop is close, but still OsmAnd makes me pass to the destination first, then first stop, and again destination 
<img src="https://user-images.githubusercontent.com/59312735/233267743-acb1cf9a-6946-4e78-b43e-d2dccbc50d56.png"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35817m, Released: 2023-04-19
`38.65435, 34.84717`

@nabilys  The route is different from the one on your screenshot
However, the route is the same, first to the 1st point, and then back to the start and finish. 
This is because the [road](https://www.openstreetmap.org/way/32392841#map=16/38.6583/34.8460) is closed to cyclists.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233335015-1b33a744-53bc-407d-9131-5b0bfe81e231.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nabilys** [comment]
So it’s an error on open street maps data?

**Comment by Zirochkabila** [comment]
@nabilys This is not a mistake - just the appropriate tags are set

**Comment by vshcherb** [comment]
@nabilys you can use plan route feature where it will ignore the restrictions for example build as pedestrian, however that's might be illegal route.
