### ISSUE TITLE
"Delete waypoints" function is expected to delete only Waypoints (do not propose to delete points of the track)

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd-iOS#2957]
### Description
When trying to delete points in track "Delete waypoints" function doesn't work. 
On Android, the deleting happens as it should.

[290Km_Rundtour (1).zip](https://github.com/osmandapp/OsmAnd-iOS/files/11819681/290Km_Rundtour.1.zip)

### Steps to reproduce

- Open track
- Points button
- Select Delete waypoints
- Select points
- Delete
- Check the result

### Actual result
After clicking the Delete button the points remain in the track

### Expected result
The points are deleted as they should be

###Your Environment
OsmAnd Version: 4.4.10.7 TestFlight \ OsmAnd 4.4.7 Android
Android/iOS version: iOS 16.0 \ Android 12

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/f237008a-4f7f-4329-af31-438219c8c1a4

**Comment by yuriiurshuliak** [comment]
Points with this track are not deleted. Points are not deleted on other tracks either.
Waypoints are successfully deleted on all tracks.

Since the function is called "delete waypoints", it accordingly deletes waypoints. Here, most likely, need to remove the ability to highlight points in tracks. In android, points are not offered for deletion in the "delete waypoints" function.
To delete points, use the plan a route functionality.
OsmAnd 4.4.10 (4.4.10.7)

<table style="width:100%">
  </tr>
  <tr>
    <th>Deleting points with a track attached to the bug</th>
    <th>Deleting points with another track</th>
    <th>Deleting Waypoints</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/6506b06b-743b-4524-bc47-d99585666c70"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/a80ff348-ca27-482f-9877-69d871a40dcc"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/3050f338-bde5-4dbb-9d04-66bc19537349"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: don't suggest "track points" to be deleted (waypoints should be still suggested to delete)

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3061

**Comment by yuriiurshuliak** [comment]
The issue has been resolved. At present, the option to remove Route points is not provided by the "delete waypoints" feature.
OsmAnd 4.5.1.3

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/acfaffba-9f82-40c9-8fc2-4ff0496f8bff
