### ISSUE TITLE
Tracks are not removed from map until profile changed

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3044]
Repro:
- show a track on the map in My places -> Tracks menu
- verify that the track is shown
- go back to My Places -> Tracks and disable display of the track
- go back to the map and observe that the track is still shown
- change map profile and observe that now the track is removed from the map

**Comment by yuriiurshuliak** [comment]
To recreate this issue, follow these steps: First, I activated the display of three tracks on the map and confirmed their visibility in two different profiles. Following that, I navigated to "My Places," then selected "My Tracks," and chose "Tracks on Map." I disabled the map display for those specific three tracks. Upon returning to the map view, I observed that these three tracks continued to appear. However, when I switched to the second profile, the expected behavior occurred, and those tracks were no longer visible as intended.

iOS 16.4.1
OsmAnd 4.4.10.7


https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/58fe263a-311d-4803-b88e-6d5a48f003e6

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3067

**Comment by yuriiurshuliak** [comment]
Repeating the identical steps mentioned earlier, did not lead to the replication of the issue in the updated Testflight version. By turning off the display of tracks, they no longer appear on the map.

OsmAnd 4.5.1.4


https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/ae1825eb-abcb-47e3-9b4e-e5be1c12f0b8
