### ISSUE TITLE
Widgets squeezed into a small space

### ISSUE THREAD

**Issue by Sertonix** [osmandapp/OsmAnd-iOS#3193]
One widget on the right side seems to be oversized and then the other widgets looks squeezed into a small space.
The device is an IPhone SE (the old one). May be related to the small screen size.

![image-20231030-215500](https://github.com/osmandapp/OsmAnd-iOS/assets/83883937/880ed9a4-f751-45e8-8710-056f7f132243)

**Comment by DmitryAlexei** [comment]
@Sertonix what is your version of the OsmAnd app?

**Comment by Sertonix** [comment]
Sorry, forgot that.
Version: 4.5.3

**Comment by DmitryAlexei** [comment]
Widget appearance have significantly improved in the latest beta builds. You can try beta using testflight (https://osmand.net/docs/versions/nightly_versions#testflight) or wait for release (hopefully soon).

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce it, activate widgets on both the right and left panels, and also enable navigation. When you do this, you'll observe that the widgets are spaced quite far apart. This issue appears to be linked to the compact screen size of the iPhone SE you're using.

Iphone 11
TestFlight OsmAnd 4.5.4.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/73cf0c75-5847-484b-bd9f-0869fb057fcc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/40fc69d3-7b1a-4224-a39d-593853f5ca2a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Probably already fixed
