### ISSUE TITLE
sqlitedb online tiles bug

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-iOS#3241]
this file created by android osmand app. it's dowlnoading tiles in android. but it's not working in ios.

[qwertyuiop.sqlitedb.zip](https://github.com/osmandapp/OsmAnd-iOS/files/13476609/qwertyuiop.sqlitedb.zip)
 
Same url in metainfo in ios works fine

<img width="300" alt="Screenshot 2023-11-27 at 19 48 50" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/71c7116c-15d0-4bbe-979c-08327f61ce6e"> <img width="300" alt="Screenshot 2023-11-27 at 19 59 00" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/8b6d2e1a-e0b1-4ad4-b6b8-3a06b741d9e7">

url:

https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I checked the tiles above, one created on Android and the other simply a link from metainfo. Currently, they both function the same way.  I imported the file above, selected it for Overlay / Underlay and specified the sqlitedb format.

OsmAnd TestFlight 4.6.2.1

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/2fd7c90f-98ec-4547-bc62-7f9d10a7195b
