### ISSUE TITLE
Exit number missing

### ISSUE THREAD

**Issue by pnoll1** [osmandapp/OsmAnd-iOS#3353]
Exit number is missing from top left.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/8444617/37cb3839-059f-422f-900b-0182df7a9ff2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/8444617/0f2c6bc2-2eab-434f-a34e-e7460da41a49"  width="300" height="auto"/> </th>
  </tr>
</table>

Reproduction:
Route from I5 north to 405 north via exit 154A

Exit is located at 47.46301, -122.26575
Osmand: 4.6.3

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced.After checking the information you provided, we didn't observe the missing exit numbers. Please clarify where exactly you see missing Exit numbers on these screenshots?

Here are the coordinates for the first and second screenshots:
47.453755225061634, -122.26393440564074
47.70261683056194, -122.17912210277564

OsmAnd Version: 4.6.4.3

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/042757a5-b6ad-4c0f-8bd0-756f76db754e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/a88a2867-908a-47ca-b0a6-c12a4d46d9db"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by pnoll1** [comment]
Issue is intermittent. I've had the numbers show up for some exits including 20B. I haven't figured out a pattern yet.

**Comment by yuriiurshuliak** [comment]
Please ensure that you have the latest version of the app installed. 
Also try updating the maps for your area. Menu → Download maps → Updates
