### ISSUE TITLE
Issue with 3D view (forced exit) 2D is not stable anymore

### ISSUE THREAD

**Issue by FarawayFerry** [osmandapp/OsmAnd-iOS#3623]
Zooming in on a track (gpx file) is currently broken in IOS 4.7 version. Zooming in and out in 2D mode is relative stable, where you can zoom and scroll through the map with a forced exit after like 20 to 50 movements on the map. However, once you switch to 3D mode Osmand performs a forced exit after just a few zooming in or out actions, rotating, or scrolling through the map.

Edit [3D is the map  displayed in 3D, not the gpx track in 3D elevation on a 2D map]

I tested it with a segmented gpx track and with a single segment gpx track, tested with a gpx track with and without elevation data, tested with and without distance markers and or direction arrows enabled (this was an issue before, and solved)

This behavior is observed on iPhone 14pro with the latest IOS operating system 17.4.1

I can not really put my finger on it, but it also seems that battery usage has increased enormously.

May I bring up that a lot of hikers use this app as their primary navigation tool and information database on where to find shelter and food in unknown territory, and that it therefore should be very carefully tested before a public release? Please make sure users can always revert to a working version.  

[apr 21, 2024 22_45.log](https://github.com/osmandapp/OsmAnd-iOS/files/15058723/apr.21.2024.22_45.log)

**Comment by DmitryAlexei** [comment]
@FarawayFerry Could you please provide more information about your issue?
- please add your profile settings (go to menu > settings > your profile where app crashes > export)
- what is the exact location on the map where a crash happens (does it depend on location?)
- short video or screenshots will be very useful

**Comment by FarawayFerry** [comment]
Here is a link to a video of the screen, me playing around with the map and gpx track switching between 2d em 3d until it crashes to the mainscreen of the phone. https://1drv.ms/v/s!Aldg16Z42L0CgY0XSSHlv1VZFk4Ofg?e=O5BQPY

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Initially, I attempted to reproduce it using default profile settings, and then I tested with your imported settings. The app functions properly in both 2D and 3D modes without crashing during rotation, scrolling, or zooming. 
Please check if you encounter the same issue using TestFlight: [link to TestFlight](https://osmand.net/docs/versions/nightly_versions#testflight).

OsmAnd TestFlight 4.7.3.10
iOS 16.4.1

<table style="width:100%">
  <tr>
  <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/43d485e6-37dc-4f3a-93ce-4c888948212d"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/dc4d928d-29ea-4cc2-a094-7e832b4e8ac0"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by FarawayFerry** [comment]
Ok, beta 4.7.3.7 seems to work ok. (I had to reboot the phone to get it working)

**Comment by yuriiurshuliak** [comment]
Please specify the specific locations where this issue occurs. Also, indicate the number of tracks visible on the map during reproducing. Additionally, attempt resetting your profile settings to default to check if this error can be replicated under default conditions.
Menu - Settings - App profile (Walking) - Reset to default

**Comment by FarawayFerry** [comment]
After resetting my profile, osmand is still exiting when zooming in or out or scrolling through the map. It is not related to a gpx track or map. I just had a forced exit without a track visible on the map. 

Oh, the compass is broken as well. (that's mentioned by other users as well)

Overall I can navigate with this version however it's far from ideal. (i don't use 3d mode when navigating but a working compass would be nice)

**Comment by juliusvaart** [comment]
I’m also having these issues. Sometimes map disappears, app hangs or just crashes when zooming or searching.

Also can’t navigate anymore. App doesn’t pick up my direction and/or compass position.

Very disappointed by this update. Same issue on Testflight and App Store versions. This is not even good enough as an alpha version.

Also tried removing and reinstalling the app, rebooting, soft reset… all the same.

Using an iPhone 13 Pro

**Comment by Dennis650** [comment]
Hello, unfortunately I have had these problems since the last update. I followed a GPX track yesterday. After scrolling or zooming, the app often freezes for 30-60 seconds, sometimes it hangs completely and has to be restarted.

iPhone SE 2nd Gen

Thank you very much for your work on this great app.

Greetings Dennis

**Comment by juliusvaart** [comment]
Seems to be working again in latest Testflight build!
