### ISSUE TITLE
Wrong icon for subway station and exit from subway station in the POI Context menu

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#3647]
OsmAnd 4.7.3.4

### Steps to reproduce
- click on a **subway station** icon on the map, open the context menu and note, whether the icon in the context menu and on the map are the same
- click on a **subway station exit** icon on the map, open the context menu and note, whether the icon in the context menu and on the map are the same
- for refernce see https://osmand.net/docs/user/map-legend/osmand#traffic-transportation

### Actual result:
- icons are different
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/11133607-cdf5-4a7f-adbe-6bf5fab638b3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/b473b15e-a91e-4d38-92cd-8903ee54b4c3"  width="300" height="auto"/> </td>
  </tr>
</table>

### To do  
For subway entrance / stations display icon subway  station (Android displays correctly)

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e4d8ab17-e3cc-4bcf-9f2f-514a07f63765"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Different icons

**Comment by nnngrach** [comment]
Issue: 
Without live updates it shows subway stop point. With live update - bus stop. Reproduces on IOS and Android.

Reproducing:
video
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/9e6d9fb2-429d-47df-811e-e4020a37f3d5
point
"Palace of Sports"  50.438289289352987 30.520867109298706

---

I have some troubles with crashing Android studio on debugging. So I tested ios version. I think android works the same way.

So when you click on the screen it search for point from the layer data. It found the same point (with and without live update). Same tags and coordinates. But it has differ "type" tag. 

Without Live Update - "public_transport_station"  - valid.
<img width="1728" alt="02 old Screenshot 2024-06-06 at 18 53 53" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/547de595-235a-49b7-bc1d-49d1989f640f">

With Live Update - "railway_station"  - invalid.
<img width="1728" alt="02 live Screenshot 2024-06-06 at 18 55 21" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/a7eec7f8-63f9-4a39-9e91-444282c4f477">

And this differ tag breaking all next logic. 

<img width="859" alt="Screenshot 2024-06-06 at 20 57 33" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/e6bb086f-f6d9-48d0-ace5-abe7f28de758">

<img width="1355" alt="Screenshot 2024-06-06 at 20 34 07" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/3f4a6589-66d3-4804-8f24-183d6af2c468">

---

If I understand correctly, the trouble is in invalid tag in live update data.

**Comment by nnngrach** [comment]
Issue: 
Without live updates it shows subway stop point. With live update - bus stop. Reproduces on IOS and Android.

Reproducing:

video: https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/9e6d9fb2-429d-47df-811e-e4020a37f3d5
point: "Palace of Sports"  50.438289289352987 30.520867109298706
map file:  Ukraine_kiev-city_europe.obf. May 2024. (I can send it if you need)

---

I have some troubles with crashing Android studio on debugging right now. So I debugged ios version only. But I think android works the same way. So here is my results.

When you click on the screen, it search for point from the layer data. It found the same point (with and without live update). Same tags and coordinates. But it has differ "typename" tag. 

Without Live Update - "public_transport_station"  - valid.
<img width="1728" alt="02 old Screenshot 2024-06-06 at 18 53 53" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/547de595-235a-49b7-bc1d-49d1989f640f">

With Live Update - "railway_station"  - invalid.
<img width="1728" alt="02 live Screenshot 2024-06-06 at 18 55 21" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/a7eec7f8-63f9-4a39-9e91-444282c4f477">

And this differ tag brake all next logic. 

<img width="859" alt="Screenshot 2024-06-06 at 20 57 33" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/e6bb086f-f6d9-48d0-ace5-abe7f28de758">

<img width="1355" alt="Screenshot 2024-06-06 at 20 34 07" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/3f4a6589-66d3-4804-8f24-183d6af2c468">

---


If I understand correctly, the trouble is in invalid typename tag in live update data. 
"railway_station" instead of "public_transport_station".

**Comment by nnngrach** [comment]
upd: 
Tested on android. selectObjectsFromOpenGl() already send invalid data.

Without Live Update - "public_transport_station" - valid.
<img width="1728" alt="Screenshot 2024-06-06 at 22 05 03" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/8a31c9f6-0f86-4b1d-ad1f-b02a04106142">

With Live Update - "railway_station" - invalid.
<img width="1728" alt="Screenshot 2024-06-06 at 22 03 22" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/2f6cb165-dcbc-44fc-91a4-4b6a7b8ef74c">
