### ISSUE TITLE
POI flicker on Carplay

### ISSUE THREAD

**Issue by ToontjeM** [osmandapp/OsmAnd-iOS#3690]
OsmAnd 4.7.5.5 on IOS 17.4.1 hooked up over CarPlay with cheap Chinese CarPlay device. 

POIs on map flicker. This is when the vehicle is not moving. Haven’t tried it yet with when moving. 

Video attached as iCloud link. 

https://share.icloud.com/photos/0b9rgdJG7HNFmQg_-lavLv-uQ

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce this issue, I activated the display of POI and simulated navigation at the lowest fixed speed. As a result, I didn't observe any flickering of the POIs. Could you please explain the exact steps needed to reproduce the issue?

TestFlight OsmAnd 4.7.5.5

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/f52d60e1-ea25-451d-b455-afdeb4c3ce86

**Comment by ToontjeM** [comment]
As you can see in the video. I don’t simulate, I don’t move. I just switch on the head unit, let it connect to my iPhone which automatically launches CarPlay, start OsmAnd and let it sit there. 
This behaviour shows on the CarPlay device, not on the phone.
