### ISSUE TITLE
Social Media on POIs non-clickable

### ISSUE THREAD

**Issue by Swamp2k9** [osmandapp/OsmAnd-iOS#3728]
When viewing POI information on click (map), I'm unable to view the social media pages.

This only occurs when the POI has a page name saved rather than the full URL.

contact:facebook

Works: 

https://facebook.com/bobsburgers

Doesn't work: bobsburgers

iPhone SE (2022, A2783)
IOS: 17.5.1 (21F90)
OsmAnd Maps: 4.7.6.3

**Comment by yuriiurshuliak** [comment]
Please provide the exact coordinates of the non-clickable POIs so we can investigate this bug on our end.

**Comment by Swamp2k9** [comment]
Working POI (with full URL):
-37.78835 175.28461

Broken POI (with Facebook page name):
-37.78944 175.28478

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. When using the provided coordinates to locate the POI, all information displayed matches OSM data. It's important to note that the coordinates -37.78944 175.28478 show outdated information because the OSM data was updated two days ago, and the app updates its maps every 30 days.

Please enable Live Updates and try again:
Menu → Maps & Resources → Updates

OsmAnd~ 4.8.0#2400m, released: 2024-05-27

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/b9015c35-cf3f-4823-9f5a-52f472cdd626"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/33163c8e-8c44-4d1d-ae9e-b8e7eb55ffa1"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Swamp2k9** [comment]
If you click the Facebook link for Tonkin POI, does the browser open up? That's the issue I'm having atm.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. I previously tested this issue on Android and did not encounter the error. However, upon testing on iOS, I observed that clicking on the Facebook link in the POI information does not work. The link is unresponsive and does not redirect to the browser.

OsmAnd TestFlight 4.7.7.1

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/4652b5f3-9206-4dd7-a96b-04e0527907b8"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/4297574d-0501-4fe3-a65a-34c08b317b79"  width="300" height="auto"/>   </td>
  </tr>
</table>
