### ISSUE TITLE
Track is not synced correct

### ISSUE THREAD

**Issue by schuessm** [osmandapp/OsmAnd-iOS#3769]
Hello,
I use the actual IOS APP in PRO-Licence. All my Tracks are not synced correct, when I create them on the Web-APP https://osmand.net/. I get only the Description an Name but no track

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to reproduce it by creating three tracks on the Web version, each with unique names and descriptions. Then, I synced all the data on my iPhone. After the synchronization completed, all three tracks showed up correctly in the app, displayed accurately on the map with their respective names and descriptions.

OsmAnd TestFlight 4.7.7.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/c0eef342-8fee-4f00-b826-e127ea35ceb4"  width="500" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/4b2b2e58-0c92-4714-a81d-88d2d1005ba5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/c985adc9-b823-404c-b53b-040e2fd06789"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by schuessm** [comment]
Ok? That’s crazy. Which Browser did you use? What operating system.

**Comment by yuriiurshuliak** [comment]
I used Google Chrome on Windows 11. 
Also, the OsmAnd version 4.7.7.1 and iOS version 16.4.1.

**Comment by dmpr0** [comment]
Hi, @schuessm !
Do you create tracks in OsmAnd Web or import theme using to OsmAnd Web?

**Comment by schuessm** [comment]
> Hi, @schuessm ! Do you create tracks in OsmAnd Web or import theme using to OsmAnd Web?

Hi @dmpr0, I create the Track on my Ubuntu machine 22.04.2 with chromium and save them to the cloud

**Comment by schuessm** [comment]
> I used Google Chrome on Windows 11. Also, the OsmAnd version 4.7.7.1 and iOS version 16.4.1.

Hi @yuriiurshuliak , hier my Screenshots from the OSMAND Web and my mobile app, i have only a version 4.7.6 an the newest version of IOS 17.5.1
![Bildschirmfoto vom 2024-06-12 08-37-22](https://github.com/osmandapp/OsmAnd-iOS/assets/16079397/283ccbd9-a765-4f99-a51e-db79aaa195f8)
![IMAGE-1](https://github.com/osmandapp/OsmAnd-iOS/assets/16079397/47342cdf-08ea-49c9-b336-eee6dccbccb1)
![IMAGE-1 (1)](https://github.com/osmandapp/OsmAnd-iOS/assets/16079397/89b908b6-84b4-4e5b-bcd6-b4ab0b9bbd5c)
![IMAGE-1 (2)](https://github.com/osmandapp/OsmAnd-iOS/assets/16079397/450f5e9f-2d92-4b02-8804-921e90d2d074)
