### ISSUE TITLE
Walking profile on ios

### ISSUE THREAD

**Issue by aqualandlover** [osmandapp/OsmAnd-iOS#3845]
Street name, map markers, and lanes, as shown on the attached screenshot, are not being displayed even though the screen is configured to show them.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0e9818ae-ed7c-44f0-8359-a718132373ab"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. In the pedestrian profile during navigation, the Street Names and Lanes widgets do not appear, though the Map Marker Bar widget functions correctly (note that a map marker is needed for it to display). You can compare how these widgets function in the car profile.

This might be expected behavior, with these widgets not intended for the pedestrian profile. However, if that’s the case, why is it possible to add them?

OsmAnd 4.7.6.3

<table style="width:100%">
  </tr>
  <tr>
    <th>Widgets in the pedestrian profile</th>
    <th>Widgets in the car profile</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/fbfea426-c2f2-4eb2-9cb5-fde2d2f9d472"  width="300" height="auto"/>   </td>
 <th><img src="https://github.com/user-attachments/assets/9404e9d7-3373-4105-924b-1e33a1e3a242"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by aqualandlover** [comment]
Is there a particular reason for rephrasing the issue? I believe the original version was clear when it was initially published.

Hand made and sent with 🌸

On Jul 15, 2024, at 13:44, yuriiurshuliak ***@***.***> wrote:

﻿

The bug has been reproduced. In the pedestrian profile during navigation, the Street Names and Lanes widgets do not appear, though the Map Marker Bar widget functions correctly (note that a map marker is needed for it to display). You can compare how these widgets function in the car profile.

This might be expected behavior, with these widgets not intended for the pedestrian profile. However, if that’s the case, why is it possible to add them?

OsmAnd 4.7.6.3

Widgets in the pedestrian profile       Widgets in the car profile
https://github.com/user-attachments/assets/fbfea426-c2f2-4eb2-9cb5-fde2d2f9d472 [https://github.com/user-attachments/assets/9404e9d7-3373-4105-924b-1e33a1e3a242] <https://github.com/user-attachments/assets/9404e9d7-3373-4105-924b-1e33a1e3a242>

**Comment by vshcherb** [comment]
Street name should work in Walking profile as it is normal navigation profile
