### ISSUE TITLE
Can not change the color of a track and keep it

### ISSUE THREAD

**Issue by WDKX0** [osmandapp/OsmAnd-iOS#3891]
I have different tracks and like to have them in different colors.
It is easy to change the color and the thickness and some other details. 

**But, how I can store the track after changing the color? When I go back every change is lost**

In the Android version is a button to safe the changes.

Thanks, Werner

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To change the color of the track, follow these steps: Tap the track → Appearance → Choose a color → At the top right of the screen, select Done.

As a result, the selected color and width are saved for the track.

OsmAnd 4.8.0.9

https://github.com/user-attachments/assets/e8a72206-36fd-4791-98ac-fd72d64f40ba

**Comment by WDKX0** [comment]
Thanks!
