### ISSUE TITLE
OsmAnd Maps fail to read apple’s map coordinates

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3978]
Steps to reproduce :
-copy coordinates from Apple Maps
-paste to OsmAnd search

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e71ef4e0-9f93-4c96-9504-7abcaafdc7a7"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4b938fc5-7ab9-4871-8fc7-abb6acc0e7ce"  width="300" height="auto"/> </td>
  </tr>
</table>   

tested with OsmAnd maps 4.8.3.0

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. Apple Maps uses the decimal degrees (DD) format, which is supported by our app. However, when copying coordinates from Apple Maps, the search fails due to extra symbols in the coordinates. For example, searching for "33.95060° S, 151.14453° E" won't yield results, but if you search using "33.95060, 151.14453" without the extra characters, the coordinates will be found. It's important to remove any additional symbols and replace commas with periods.

OsmAnd 4.8.3.0

https://github.com/user-attachments/assets/c737283f-4fa0-408d-96a4-8ca07a3b6e06

**Comment by yuriiurshuliak** [comment]
While we separately support some Google formats, it’s important to support this format as well.

**Comment by vshcherb** [comment]
```15,123, 23,12``` -> ```15.123, 23.12```

**Comment by RZR-UA** [comment]
- [ ] ios
- [x] android
